In [ ]:
import numpy as np
import pandas as pd

pd.set_option("display.max.columns", 100)
# to draw pictures in jupyter notebook
%matplotlib inline
# we don't like warnings
# you can comment the following 2 lines if you'd like to
import warnings

import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

In [ ]:
# for Jupyter-book, we copy data from GitHub, locally, to save Internet traffic,
# you can specify the data/ folder from the root of your cloned
# https://github.com/Yorko/mlcourse.ai repo, to save Internet traffic
DATA_URL = "https://raw.githubusercontent.com/Yorko/mlcourse.ai/main/data/"

In [ ]:
data = pd.read_csv(DATA_URL + "adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

1. How many men and women (sex feature) are represented in this dataset?

In [ ]:
df = data.copy()

df['sex'].describe()
df['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

2. What is the average age (age feature) of women?

In [ ]:
df_age = df.groupby('sex', as_index=False)['age'].mean()
df_age[df_age['sex'] == 'Female']

      sex    age
0  Female  36.86

3. What is the percentage of German citizens (native-country feature)?

In [ ]:
df_country = df['native-country'].value_counts(normalize=True)
df_country[df_country.index == 'Germany']

native-country
Germany    4.21e-03
Name: proportion, dtype: float64

4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (salary feature) and those who earn less than 50K per year?

In [ ]:
df['salary'].describe()

df_salary_stats = df.groupby('salary')['age'].describe(percentiles=[])
df_salary_stats[['mean', 'std']]

         mean    std
salary
<=50K   36.78  14.02
>50K    44.25  10.52

6. Is it true that people who earn more than 50K have at least high school education? (education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate feature)

In [ ]:
df['education'].value_counts()

below_HS = [
    "Preschool",
    "1st-4th",
    "5th-6th",
    "7th-8th",
    "9th",
    "10th",
    "11th",
    "12th",
]

def is_high_salary_without_HS(df):
    if ((df['salary'] == '>=50K') & (~df['education'].isin(below_HS))).any():
        print("Yes")
    else:
        print("No")

is_high_salary_without_HS(df)

No

7. Display age statistics for each race (race feature) and each gender (sex feature). Use groupby() and describe(). Find the maximum age of men of Amer-Indian-Eskimo race.

In [ ]:
df.groupby(['race', 'sex']).describe()

                               age                                         \
                             count   mean    std   min   25%   50%    75%
race               sex
Amer-Indian-Eskimo Female    119.0  37.12  13.11  17.0  27.0  36.0  46.00
                   Male      192.0  37.21  12.05  17.0  28.0  35.0  45.00
Asian-Pac-Islander Female    346.0  35.09  12.30  17.0  25.0  33.0  43.75
                   Male      693.0  39.07  12.88  18.0  29.0  37.0  46.00
Black              Female   1555.0  37.85  12.64  17.0  28.0  37.0  46.00
                   Male     1569.0  37.68  12.88  17.0  27.0  36.0  46.00
Other              Female    109.0  31.68  11.63  17.0  23.0  29.0  39.00
                   Male      162.0  34.65  11.36  17.0  26.0  32.0  42.00
White              Female   8642.0  36.81  14.33  17.0  25.0  35.0  46.00
                   Male    19174.0  39.65  13.44  17.0  29.0  38.0  49.00

                                  fnlwgt                                 \
                            max    count       mean        std      min
race               sex
Amer-Indian-Eskimo Female  80.0    119.0  112950.73   93207.97  12285.0
                   Male    82.0    192.0  125715.36   85063.25  13769.0
Asian-Pac-Islander Female  75.0    346.0  147452.08   76401.63  19914.0
                   Male    90.0    693.0  166175.87   88552.95  14878.0
Black              Female  90.0   1555.0  212971.39  109971.26  19752.0
                   Male    90.0   1569.0  242920.64  134145.97  21856.0
Other              Female  74.0    109.0  172519.64   77766.67  24562.0
                   Male    77.0    162.0  213679.10   92187.36  25610.0
White              Female  90.0   8642.0  183549.97  101710.29  19395.0
                   Male    90.0  19174.0  188987.39  103714.60  18827.0

                                                                     \
                                 25%       50%        75%       max
race               sex
Amer-Indian-Eskimo Female   31387.00   87950.0  163027.50  4.45e+05
                   Male     48197.75  113091.0  182656.00  3.56e+05
Asian-Pac-Islander Female   86879.25  131986.0  175705.75  3.79e+05
                   Male     98350.00  147719.0  200117.00  5.06e+05
Black              Female  142666.50  193553.0  253759.00  9.31e+05
                   Male    156410.00  221196.0  298601.00  1.27e+06
Other              Female  119890.00  171199.0  219441.00  3.89e+05
                   Male    150726.75  208516.5  253334.75  4.81e+05
White              Female  115914.75  175810.5  224836.50  1.48e+06
                   Male    117381.00  178662.5  236858.75  1.46e+06

                          education-num                                     \
                                  count   mean   std  min  25%   50%   75%
race               sex
Amer-Indian-Eskimo Female         119.0   9.70  2.33  2.0  9.0  10.0  11.0
                   Male           192.0   9.07  2.27  2.0  9.0   9.0  10.0
Asian-Pac-Islander Female         346.0  10.39  2.80  1.0  9.0  10.0  13.0
                   Male           693.0  11.25  2.78  1.0  9.0  11.0  13.0
Black              Female        1555.0   9.55  2.21  1.0  9.0   9.0  10.0
                   Male          1569.0   9.42  2.38  1.0  9.0   9.0  10.0
Other              Female         109.0   8.90  3.03  2.0  7.0   9.0  10.0
                   Male           162.0   8.80  3.36  1.0  8.0   9.0  10.0
White              Female        8642.0  10.13  2.37  1.0  9.0  10.0  12.0
                   Male         19174.0  10.14  2.66  1.0  9.0  10.0  13.0

                                capital-gain                               \
                            max        count     mean       std  min  25%
race               sex
Amer-Indian-Eskimo Female  16.0        119.0   544.61   2451.59  0.0  0.0
                   Male    16.0        192.0   675.26   2929.75  0.0  0.0
Asian-Pac-Islander Female  15.0        346.0   778.44   7675.23  0.0  0.0
                   Male    16.0        693.0  1827.81  10947.53  0.0  0.0
Black              Female  16.0       1555.0   516.59   5312.75  0.0  0.0
                   Male    16.0       1569.0   702.45   4962.11  0.0  0.0
Other              Female  14.0        109.0   254.67   1317.33  0.0  0.0
                   Male    16.0        162.0  1392.19  11093.71  0.0  0.0
White              Female  16.0       8642.0   573.61   4763.13  0.0  0.0
                   Male    16.0      19174.0  1368.67   8442.83  0.0  0.0

                                             capital-loss                  \
                           50%  75%      max        count    mean     std
race               sex
Amer-Indian-Eskimo Female  0.0  0.0  15024.0        119.0   14.46  157.76
                   Male    0.0  0.0  27828.0        192.0   46.40  286.56
Asian-Pac-Islander Female  0.0  0.0  99999.0        346.0   50.85  296.53
                   Male    0.0  0.0  99999.0        693.0  120.37  472.92
Black              Female  0.0  0.0  99999.0       1555.0   45.45  299.10
                   Male    0.0  0.0  99999.0       1569.0   75.19  370.98
Other              Female  0.0  0.0   7688.0        109.0   36.28  231.80
                   Male    0.0  0.0  99999.0        162.0   77.75  370.99
White              Female  0.0  0.0  99999.0       8642.0   65.39  352.33
                   Male    0.0  0.0  99999.0      19174.0  102.26  434.16

                                                      hours-per-week         \
                           min  25%  50%  75%     max          count   mean
race               sex
Amer-Indian-Eskimo Female  0.0  0.0  0.0  0.0  1721.0          119.0  36.58
                   Male    0.0  0.0  0.0  0.0  1980.0          192.0  42.20
Asian-Pac-Islander Female  0.0  0.0  0.0  0.0  2258.0          346.0  37.44
                   Male    0.0  0.0  0.0  0.0  2457.0          693.0  41.47
Black              Female  0.0  0.0  0.0  0.0  4356.0         1555.0  36.83
                   Male    0.0  0.0  0.0  0.0  2824.0         1569.0  40.00
Other              Female  0.0  0.0  0.0  0.0  1740.0          109.0  35.93
                   Male    0.0  0.0  0.0  0.0  2179.0          162.0  41.85
White              Female  0.0  0.0  0.0  0.0  4356.0         8642.0  36.30
                   Male    0.0  0.0  0.0  0.0  3770.0        19174.0  42.67


                             std  min   25%   50%   75%   max
race               sex
Amer-Indian-Eskimo Female  11.05  4.0  35.0  40.0  40.0  84.0
                   Male    11.60  3.0  40.0  40.0  45.0  84.0
Asian-Pac-Islander Female  12.48  1.0  35.0  40.0  40.0  99.0
                   Male    12.39  1.0  40.0  40.0  45.0  99.0
Black              Female   9.42  2.0  35.0  40.0  40.0  99.0
                   Male    10.91  1.0  40.0  40.0  40.0  99.0
Other              Female  10.30  6.0  30.0  40.0  40.0  65.0
                   Male    11.08  5.0  40.0  40.0  40.0  98.0
White              Female  12.19  1.0  30.0  40.0  40.0  99.0
                   Male    12.19  1.0  40.0  40.0  50.0  99.0

In [ ]:
df_max_age = df.groupby(['race', 'sex'], as_index=False).describe()

df_max_age[(df_max_age['race'] == 'Amer-Indian-Eskimo') & (df_max_age['sex'] == 'Male')]['age']['max']

1    82.0
Name: max, dtype: float64

8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (marital-status feature)? Consider as married those who have a marital-status starting with Married (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.

In [ ]:
df['marital-status'].value_counts()

df['married_or_single'] = df['marital-status'].apply(lambda x: 'Married' if x.startswith('Married') else 'Single')

df[(df['sex'] == 'Male') & (df['salary'] == '>50K')]['married_or_single'].value_counts()

df_find_men = df[(df['sex'] == 'Male') & (df['salary'] == '>50K')]['married_or_single'].value_counts()

df_find_men

married_or_single
Married    5965
Single      697
Name: count, dtype: int64

In [ ]:
if df_find_men['Married'] > df_find_men['Single']:
    print("Married")
else:
    print("Single")

Married

9. What is the maximum number of hours a person works per week (hours-per-week feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?

In [ ]:
df['hours-per-week'].value_counts().sort_index(ascending=False)

df_hours = df['hours-per-week'].value_counts().sort_index(ascending=False)

df_hours.index.max()

np.int64(99)

In [ ]:
df_hours.loc[df_hours.index.max()]

np.int64(85)

In [ ]:
df[df['hours-per-week'] == df_hours.index.max()]['salary'].value_counts(normalize=True)['>50K']

np.float64(0.29411764705882354)

10. Count the average time of work (hours-per-week) for those who earn a little and a lot (salary) for each country (native-country). What will these be for Japan?

In [ ]:
df.groupby(['native-country', 'salary'])['hours-per-week'].mean()

native-country  salary
?               <=50K     40.16
                >50K      45.55
Cambodia        <=50K     41.42
                >50K      40.00
Canada          <=50K     37.91
                          ...
United-States   >50K      45.51
Vietnam         <=50K     37.19
                >50K      39.20
Yugoslavia      <=50K     41.60
                >50K      49.50
Name: hours-per-week, Length: 82, dtype: float64

In [ ]:
df.groupby(['native-country', 'salary'])['hours-per-week'].mean().loc['Japan']

salary
<=50K    41.00
>50K     47.96
Name: hours-per-week, dtype: float64