In [1]:
import os
import warnings

warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import requests
from plotly import __version__
from plotly import graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot, plot
from IPython.display import display, IFrame

print(__version__)  # need 1.9.0 or greater
init_notebook_mode(connected=True)

6.8.0

In [2]:
def plotly_df(df, title="", width=800, height=500):
    """Visualize all the dataframe columns as line plots."""
    common_kw = dict(x=df.index, mode="lines")
    data = [go.Scatter(y=df[c], name=c, **common_kw) for c in df.columns]
    layout = dict(title=title)
    fig = dict(data=data, layout=layout)

    # in a Jupyter Notebook, the following should work
    #iplot(fig, show_link=False)

    # in a Jupyter Book, we save a plot offline and then render it with IFrame
    plot_path = f"../../_static/plotly_htmls/{title}.html".replace(" ", "_")
    plot(fig, filename=plot_path, show_link=False, auto_open=False);
    display(IFrame(plot_path, width=width, height=height))

### Data preparation

In [3]:
# for Jupyter-book, we copy data from GitHub, locally, to save Internet traffic,
# you can specify the data/ folder from the root of your cloned
# https://github.com/Yorko/mlcourse.ai repo, to save Internet traffic
DATA_PATH = "https://raw.githubusercontent.com/Yorko/mlcourse.ai/main/data/"

In [4]:
df = pd.read_csv(DATA_PATH + "wiki_machine_learning.csv", sep=" ")
df = df[df["count"] != 0]
df.head()

          date  count lang              page  rank   month             title
81  2015-01-01   1414   en  Machine_learning  8708  201501  Machine_learning
80  2015-01-02   1920   en  Machine_learning  8708  201501  Machine_learning
79  2015-01-03   1338   en  Machine_learning  8708  201501  Machine_learning
78  2015-01-04   1404   en  Machine_learning  8708  201501  Machine_learning
77  2015-01-05   2264   en  Machine_learning  8708  201501  Machine_learning

In [5]:
df.shape

(383, 7)

### Predicting with FB Prophet

In [6]:
df.date = pd.to_datetime(df.date)

In [8]:
def plotly_df(df, title="", width=800, height=500):
    """Visualize all the dataframe columns as line plots."""
    common_kw = dict(x=df.index, mode="lines")
    data = [go.Scatter(y=df[c], name=c, **common_kw) for c in df.columns]
    layout = dict(title=title)
    fig = dict(data=data, layout=layout)

    iplot(fig)

In [9]:
plotly_df(df=df.set_index("date")[["count"]], title="assign9_plot")

In [11]:
# !pip install prophet

Collecting prophet
  Downloading prophet-1.3.0-py3-none-win_amd64.whl.metadata (3.6 kB)
Collecting cmdstanpy>=1.0.4 (from prophet)
  Downloading cmdstanpy-1.3.0-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: numpy>=1.15.4 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from prophet) (2.4.6)
Requirement already satisfied: matplotlib>=2.0.0 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from prophet) (3.11.0)
Requirement already satisfied: pandas>=1.0.4 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from prophet) (3.0.3)
Collecting holidays<1,>=0.25 (from prophet)
  Downloading holidays-0.102-py3-none-any.whl.metadata (54 kB)
Requirement already satisfied: tqdm>=4.36.1 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from prophet) (4.68.3)
Collecting importlib_resources (from prophet)
  Downloading importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from holidays<1,>=0.25->prophet) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from python-dateutil<3,>=2.9.0.post0->holidays<1,>=0.25->prophet) (1.17.0)
Collecting stanio<2.0.0,>=0.4.0 (from cmdstanpy>=1.0.4->prophet)
  Downloading stanio-0.5.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from matplotlib>=2.0.0->prophet) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from matplotlib>=2.0.0->prophet) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from matplotlib>=2.0.0->prophet) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from matplotlib>=2.0.0->prophet) (26.2)
Requirement already satisfied: pillow>=9 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from matplotlib>=2.0.0->prophet) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from matplotlib>=2.0.0->prophet) (3.3.2)
Requirement already satisfied: tzdata in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from pandas>=1.0.4->prophet) (2026.2)
Requirement already satisfied: colorama in C:\temp\python_learning\mlcourse_ai\.venv\Lib\site-packages (from tqdm>=4.36.1->prophet) (0.4.6)
Downloading prophet-1.3.0-py3-none-win_amd64.whl (12.1 MB)
   ---------------------------------------- 0.0/12.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.1 MB ? eta -:--:--
    --------------------------------------- 0.3/12.1 MB ? eta -:--:--
    --------------------------------------- 0.3/12.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.1 MB 516.7 kB/s eta 0:00:23
   - -------------------------------------- 0.5/12.1 MB 516.7 kB/s eta 0:00:23
   -- ------------------------------------- 0.8/12.1 MB 583.1 kB/s eta 0:00:20
   -- ------------------------------------- 0.8/12.1 MB 583.1 kB/s eta 0:00:20
   --- ------------------------------------ 1.0/12.1 MB 628.0 kB/s eta 0:00:18
   ---- ----------------------------------- 1.3/12.1 MB 647.5 kB/s eta 0:00:17
   ---- ----------------------------------- 1.3/12.1 MB 647.5 kB/s eta 0:00:17
   ----- ---------------------------------- 1.6/12.1 MB 684.1 kB/s eta 0:00:16
   ------ --------------------------------- 1.8/12.1 MB 716.3 kB/s eta 0:00:15
   ------ --------------------------------- 2.1/12.1 MB 735.2 kB/s eta 0:00:14
   ------ --------------------------------- 2.1/12.1 MB 735.2 kB/s eta 0:00:14
   ------- -------------------------------- 2.4/12.1 MB 755.5 kB/s eta 0:00:13
   -------- ------------------------------- 2.6/12.1 MB 748.9 kB/s eta 0:00:13
   --------- ------------------------------ 2.9/12.1 MB 783.4 kB/s eta 0:00:12
   --------- ------------------------------ 2.9/12.1 MB 783.4 kB/s eta 0:00:12
   ---------- ----------------------------- 3.1/12.1 MB 794.3 kB/s eta 0:00:12
   ----------- ---------------------------- 3.4/12.1 MB 815.7 kB/s eta 0:00:11
   ----------- ---------------------------- 3.4/12.1 MB 815.7 kB/s eta 0:00:11
   ------------ --------------------------- 3.9/12.1 MB 856.3 kB/s eta 0:00:10
   ------------- -------------------------- 4.2/12.1 MB 852.9 kB/s eta 0:00:10
   -------------- ------------------------- 4.5/12.1 MB 859.6 kB/s eta 0:00:09
   --------------- ------------------------ 4.7/12.1 MB 910.6 kB/s eta 0:00:09
   ----------------- ---------------------- 5.2/12.1 MB 940.7 kB/s eta 0:00:08
   ----------------- ---------------------- 5.2/12.1 MB 940.7 kB/s eta 0:00:08
   ------------------ --------------------- 5.5/12.1 MB 943.4 kB/s eta 0:00:08
   ------------------- -------------------- 6.0/12.1 MB 980.8 kB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.1 MB 985.4 kB/s eta 0:00:06
   --------------------- ------------------ 6.6/12.1 MB 1.0 MB/s eta 0:00:06
   ----------------------- ---------------- 7.1/12.1 MB 1.0 MB/s eta 0:00:05
   ------------------------ --------------- 7.3/12.1 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 7.6/12.1 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 7.6/12.1 MB 1.1 MB/s eta 0:00:05
   -------------------------- ------------- 8.1/12.1 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 8.1/12.1 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 8.4/12.1 MB 1.1 MB/s eta 0:00:04
   ----------------------------- ---------- 8.9/12.1 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 9.7/12.1 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 10.0/12.1 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 10.5/12.1 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 10.7/12.1 MB 1.2 MB/s eta 0:00:02
   ------------------------------------- -- 11.3/12.1 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.1 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 12.1/12.1 MB 1.2 MB/s  0:00:10
Downloading holidays-0.102-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 2.3 MB/s  0:00:00
Downloading cmdstanpy-1.3.0-py3-none-any.whl (99 kB)
Downloading stanio-0.5.1-py3-none-any.whl (8.1 kB)
Downloading importlib_resources-7.1.0-py3-none-any.whl (37 kB)
Installing collected packages: stanio, importlib_resources, holidays, cmdstanpy, prophet

   -------- ------------------------------- 1/5 [importlib_resources]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ---------------- ----------------------- 2/5 [holidays]
   ------------------------ --------------- 3/5 [cmdstanpy]
   ------------------------ --------------- 3/5 [cmdstanpy]
   -------------------------------- ------- 4/5 [prophet]
   -------------------------------- ------- 4/5 [prophet]
   -------------------------------- ------- 4/5 [prophet]
   -------------------------------- ------- 4/5 [prophet]
   -------------------------------- ------- 4/5 [prophet]
   -------------------------------- ------- 4/5 [prophet]
   -------------------------------- ------- 4/5 [prophet]
   -------------------------------- ------- 4/5 [prophet]
   ---------------------------------------- 5/5 [prophet]

Successfully installed cmdstanpy-1.3.0 holidays-0.102 importlib_resources-7.1.0 prophet-1.3.0 stanio-0.5.1

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
from prophet import Prophet

In [13]:
predictions = 30

df = df[["date", "count"]]
df.columns = ["ds", "y"]
df.tail()

            ds     y
382 2016-01-16  1644
381 2016-01-17  1836
376 2016-01-18  2983
375 2016-01-19  3389
372 2016-01-20  3559

Question 1: What is the prediction of the number of views of the wiki page on January 20? Round to the nearest integer.

In [16]:
train_df = df[:-predictions]
m = Prophet()

m.fit(train_df)

future = m.make_future_dataframe(periods=predictions)

forecast = m.predict(future)
forecast[forecast['ds'] == '2016-01-20'][['ds','yhat']]

round(forecast[forecast['ds'] == '2016-01-20']['yhat'].values[0])

17:08:05 - cmdstanpy - INFO - Chain [1] start processing
17:08:06 - cmdstanpy - INFO - Chain [1] done processing

3422

In [ ]:
all_Predictions = m.pre

Answer: 3426.

Question 2: What is MAPE equal to?

In [19]:
from sklearn.metrics import mean_absolute_percentage_error

In [ ]:
mape = mean_absolute_percentage_error()

mape(df['y'][-predictions:], forecast['yhat'])

TypeError: missing a required argument: 'y_true'